# config/app.yml for rails-settings-cached
defaults: &defaults
  proxyIp: "brito.tplinkdns.com"
  proxyPort: "3128"
  showJobs: false

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
